#!/usr/bin/env bash
# Clean local-dev launcher for the BookStack validation stack on THIS machine
# (laptop/workstation, not connor-server). Wired to the VSCode "Deploy BookStack"
# run button (.vscode/launch.json) and tasks (.vscode/tasks.json).
#
# Idempotent: bootstraps deploy/local/.env if missing (localhost on a non-privileged
# port, generated APP_KEY + random DB passwords), brings the stack up, waits until
# BookStack actually serves its first request (first-run migrations finish), then
# opens it in a browser.
#
#   ./dev-up.sh           # up (keeps existing data) + wait + open
#   ./dev-up.sh --fresh   # wipe volumes first → from-scratch deploy
#   NO_OPEN=1 ./dev-up.sh # don't open a browser (headless / CI)
#   PULL=1 ./dev-up.sh    # docker compose pull first (fetch a bumped image pin, e.g. on a deploy)
#
# Note: the canonical image pins live in tests/integration/run.sh and are mirrored in
# .env.example (see CLAUDE.md "No floating :latest"); this script reads them from
# .env.example so a generated .env tracks the validated versions.
set -euo pipefail

cd "$(dirname "$0")"

FRESH=0
for arg in "$@"; do
  case "$arg" in
    --fresh | -f) FRESH=1 ;;
    *)
      echo "unknown argument: $arg (expected --fresh)" >&2
      exit 2
      ;;
  esac
done

# --- 1. Ensure .env exists (generate a local-dev one if missing) -------------
if [ ! -f .env ]; then
  echo "==> No .env found; generating a local-dev .env (http://localhost:8080)"
  bs_tag=$(grep -E '^BOOKSTACK_TAG=' .env.example | cut -d= -f2-)
  db_tag=$(grep -E '^MARIADB_TAG=' .env.example | cut -d= -f2-)
  app_key=$(docker run --rm --entrypoint /bin/bash "lscr.io/linuxserver/bookstack:${bs_tag}" appkey |
    grep -oE 'base64:[A-Za-z0-9+/=]+' | head -1)
  cat > .env <<EOF
# Generated by dev-up.sh for local dev on this machine. Gitignored — never commit.
BOOKSTACK_TAG=${bs_tag}
MARIADB_TAG=${db_tag}
TZ=America/Chicago
APP_NAME=CCC Wiki
APP_URL=http://localhost:8080
HTTP_BIND=8080
APP_KEY=${app_key}
DB_ROOT_PASSWORD=root-$(openssl rand -hex 12)
DB_DATABASE=bookstackapp
DB_USERNAME=bookstack
DB_PASSWORD=app-$(openssl rand -hex 12)
AUTH_METHOD=standard
AUTH_AUTO_INITIATE=false
REVISION_LIMIT=false
EOF
fi

# The URL we browse to and poll for readiness (must match HTTP_BIND in .env).
app_url=$(grep -E '^APP_URL=' .env | cut -d= -f2-)
app_url=${app_url:-http://localhost:8080}

# --- 2. (optional) wipe for a from-scratch deploy ----------------------------
if [ "$FRESH" -eq 1 ]; then
  echo "==> --fresh: removing containers + volumes (deletes all local wiki data)"
  docker compose down -v
fi

# --- 3. bring the stack up ---------------------------------------------------
# PULL=1 refreshes pinned images first (used by deploys so a bumped BOOKSTACK_TAG /
# MARIADB_TAG in .env is actually fetched). Default off so local dev stays fast/offline.
if [ "${PULL:-0}" = "1" ]; then
  echo "==> PULL=1: docker compose pull"
  docker compose pull
fi
echo "==> docker compose up -d"
docker compose up -d

# --- 4. wait until BookStack serves (DB-free static asset, like the prod health check) ---
echo "==> waiting for BookStack at ${app_url} (first-run migrations can take ~30s) ..."
ready=0
for _ in $(seq 1 90); do
  code=$(curl -s -o /dev/null -w '%{http_code}' "${app_url}/icon.png" 2> /dev/null || echo 000)
  if [ "$code" = "200" ]; then
    ready=1
    break
  fi
  sleep 2
done
if [ "$ready" -ne 1 ]; then
  echo "!! BookStack did not become ready in time. Recent app logs:" >&2
  docker compose logs --tail=30 bookstack >&2 || true
  exit 1
fi

echo "==> BookStack is up: ${app_url}"
echo "    First login: admin@admin.com / password  (change it immediately)"

# --- 5. open a browser (best-effort; suppress with NO_OPEN=1) ----------------
if [ "${NO_OPEN:-0}" != "1" ]; then
  if command -v open > /dev/null 2>&1; then
    open "$app_url"
  elif command -v xdg-open > /dev/null 2>&1; then
    xdg-open "$app_url"
  fi
fi
